my_tuple = ()
print(my_tuple)
my_tuple = (1, 2, 3)
print(my_tuple)
my_tuple = (1, "Hello", 3.4)
print(my_tuple)
my_tuple = ("Mouse", [8, 2, 1], (3, 2, 1))
print(my_tuple)
my_tuple = ("p", "e", "r", "m", "i", "t")
print(my_tuple[0])
print(my_tuple[5])
n_tuple = ("Mouse", [8, 2, 1], (3, 2, 1))

print(n_tuple[1][1])
print("Sliced:", my_tuple[1:4])
for letter in (my_tuple):
    print("Hello", letter)
